database:
    host: localhost
    port: 3306
    user: awesome-user
    password: with-bigger-secret-password
    name: on-amawing-database
    debug: false
    persistent: false
api:
    debug: true
smtp:
    host:
    port:
    secure:
    username:
    password:
    from: